// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: test.sql

package repository

import (
	"context"
)

const test = `-- name: Test :exec
SELECT 1
`

func (q *Queries) Test(ctx context.Context) error {
	_, err := q.db.Exec(ctx, test)
	return err
}
